trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  solutionFile: $(Build.SourcesDirectory)\src\Todo.CLI.sln
  projectDirectory: $(Build.SourcesDirectory)\src\Todo.CLI

steps:
- script: dotnet build $(solutionFile) --configuration $(buildConfiguration)
  displayName: 'Build solution'