trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  solution: $(Build.SourcesDirectory)/src/Todo.CLI.sln
  projectDirectory: $(Build.SourcesDirectory)/src/Todo.CLI 

steps:
- script: dotnet build $solution --configuration $(buildConfiguration)
  displayName: 'dotnet build $solution $(buildConfiguration)'
- script: dotnet publish $projectDirectory --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet publish $projectDirectory $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'todo-cli'
    publishLocation: 'Container'