name: 0.1.0$(rev:.r)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  solutionFile: $(Build.SourcesDirectory)/src/Todo.CLI.sln
  projectDirectory: $(Build.SourcesDirectory)/src/Todo.CLI/
  runtimeIdentifier: osx-x64
  outputDirectory: $(Build.ArtifactStagingDirectory)/$(runtimeIdentifier)/
  artifactName: 'todo.$(Build.BuildNumber).$(runtimeIdentifier)'

steps:
- script: dotnet publish $(projectDirectory) -c $(buildConfiguration) -r $(runtimeIdentifier) -o $(outputDirectory) /p:Version=$(Build.BuildNumber) --self-contained true
  displayName: 'Publish self-contained executable for $(runtimeIdentifier)'
- publish: '$(outputDirectory)'
  displayName: 'Publish artefact for $(runtimeIdentifier)'
  artifact: '$(artifactName)'