name: 0.0.0$(rev:.r)

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  solutionFile: $(Build.SourcesDirectory)/src/Todo.CLI.sln
  projectDirectory: $(Build.SourcesDirectory)/src/Todo.CLI/
  runtimeIdentifier: win10-x64
  outputDirectory: $(Build.ArtifactStagingDirectory)/$(runtimeIdentifier)/

steps:
- script: dotnet publish $(projectDirectory) -c $(buildConfiguration) -r $(runtimeIdentifier) -o $(outputDirectory) --self-contained true
  displayName: 'Publish as self-contained executable for $(runtimeIdentifier)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish artefact for $(runtimeIdentifier)'
  inputs:
    PathtoPublish: '$(outputDirectory)'
    ArtifactName: 'todo-cli.$(runtimeIdentifier)'
    publishLocation: 'Container'
